### ISSUE TITLE
LintCheck warning about handled CompositeDisposables

### ISSUE THREAD

**Issue by xxfast** [uber/AutoDispose#331] opened 2019-02-12 00:54 UTC
Version: **1.1.0**:

LintChecker still warns even when the composite disposable is disposed

```kotlin
class MainActivity : AppCompatActivity() {
   private val disposables = CompositeDisposable()
   override fun onCreate(savedInstanceState: Bundle?) {
      disposables += Observable.just(...)
           .subscribe { }
   }
   override fun onDestroy() {
      disposables.clear()
   }
```

**Comment by ZacSweers** [comment] 2019-02-12 01:14
@shaishavgandhi05 want to take a look? My guess is we have a hardcoded `io.reactivex.Disposable` check when it should be any implementer of that interface

**Comment by shaishavgandhi05** [comment] 2019-02-12 01:19
Will take a look!

**Comment by shaishavgandhi05** [comment] 2019-02-12 05:38
@xxfast I wasn't able to reproduce. Do you have Lenient mode on?

Check out the Wiki about the [Lenient mode](https://github.com/uber/AutoDispose/wiki/Lint-Check#lenient). It will allow the lint to not raise an error when you handle the `Disposable` yourself.

**Comment by shaishavgandhi05** [comment] 2019-02-16 16:49
Gonna close this for now. Feel free to reopen if the Lenient Mode didn't work for you.

**Closed by shaishavgandhi05** 2019-02-16 16:49 UTC

**Comment by vovkab** [comment] 2019-03-21 00:56
We are also experiencing this bug.

It's very easy to reproduce, just add disposable to `CompositeDisposable`:

```
private final CompositeDisposable disposables = new CompositeDisposable();
disposables.add(Observable.just("").subscribe());
```

Error:

```
Error: Missing Disposable handling: Apply AutoDispose or cache the Disposable instance manually and enable lenient mode. [AutoDispose]
          disposables.add(Observable.just("").subscribe());
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Here is repro project:
https://github.com/vovkab/autodispose-lint-error/commit/c128e240399bda2e4bef8f7dfb7de9a0f4f146d3

**Comment by shaishavgandhi05** [comment] 2019-03-21 02:24
Thanks for the repro project. You'll have to add the `autodispose.lenient=true` flag in an **app-level** `gradle.properties` file. The Wiki should make this clearer; I'll edit it to reflect that. 

I've made a PR on your fork. That should fix the build.

**Comment by vovkab** [comment] 2019-03-21 17:53
@shaishavgandhi05 thanks for a quick response!

A couple of suggestions:
* Maybe we could support both root project and subproject level properties? This way we could set default and override in subprojects that we need.
* Since it's a gradle terminology, maybe we could use "subproject" instead of "app-level" to make it more clear, or maybe "per project". But if we add support for (1) this would be less of an issue I think.

Anyway, thanks for the help!
