### ISSUE TITLE
Unsubscribe to ON_PAUSE

### ISSUE THREAD

**Issue by dmitro-ivanov** [uber/AutoDispose#367] opened 2019-08-09 16:04 UTC
**Library version**: 1.0.0

**Repro steps or stacktrace**:
I have an activity class and a Coordinator class. I passed instance of activity lifecycle through the constructor to coordinator. Then inside init function, i subscribed to lifecycle, when onStart method called. I supposed that this subscription will bind to onStart -> onStop, however it was bind to onResume -> onPause. 
Here is a little bit an example from my app.

```kotlin
class Coordinator(
    private val lifecycle: Lifecycle // Activity lifecycle
) : LifecycleObserver {
    private val scope: ScopeProvider = AndroidLifecycleScopeProvider.from(lifecycle)

    init {
        lifecycle.addObserver(this)
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_START)
    fun onStart() {
        // This subscription will dispose when onPause happen. But why? I am making 
        // subscribe inside ON_START event
        controller
            .watcher
            .rxProfile
            .autoDisposable(scope)
            .subscribe()
    }
}
```

**Comment by ZacSweers** [comment] 2019-08-09 16:24
My memory is fuzzy, but can you set a breakpoint in your onStart callback
and see what the current lifecycle state is? I think it will still say
CREATED

**Comment by walker622** [comment] 2019-08-09 16:34
<img width="471" alt="Screenshot 2019-08-09 at 19 32 45" src="https://user-images.githubusercontent.com/40494622/62794338-834ddb80-badc-11e9-9426-b645d457e63a.png">
No, it is STARTED.

**Comment by walker622** [comment] 2019-08-09 16:36
Probably the problem because of backfillEvents(), which set ON_RESUME event if the currentState is STARTED or RESUMED.

**Comment by walker622** [comment] 2019-08-14 11:53
Could anyone give me feedback?

**Comment by ZacSweers** [comment] 2019-08-14 16:51
Can you provide a minimal repro project one of us could build and debug for ourselves?

**Comment by walker622** [comment] 2019-08-19 10:17
> Can you provide a minimal repro project one of us could build and debug for ourselves?

Sure, here is an example of issue. https://github.com/walker622/auto-dispose-issue

**Comment by ZacSweers** [comment] 2019-08-22 03:57
Hey @walker622 - just a bit of feedback, that project is using an old version of autodispose, and quite old versions of other tools. It makes it easier for use to test if we don't have to update the project to modern versions of things just to open it in the IDE. Advice for the future, I'm going to look at this soon

**Comment by ZacSweers** [comment] 2019-08-22 04:03
I'm actually unable to build that project as-is even with the build updates

```
FAILURE: Build failed with an exception.

* What went wrong:
buildOutput.apkData must not be null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

In order for us to investigate this, please update the sample project to be buildable with the latest stable android studio, android gradle plugin plugin, autodispose version, and arch components versions. Please also supply a build command we can use and exact instructions for where to breakpoint and what to check to reproduce this problem.

**Comment by ZacSweers** [comment] 2019-08-22 05:06
I've been digging in separately, and the best answer I can come up with is this:

the current behavior is designed for `onCreate()`, `onStart()`, etc callbacks. Unfortunately with those callbacks, they're currently implemented in androidx such that the current lifecycle state is still the previous. That is - state during `onCreate()` is `INITIALIZED`, and during `onStart()` it's `CREATED`. In `LifecycleObserver`s though, these report `CREATED` and `STARTED` during their event callbacks. I think this is an inconsistency in androidx.lifecycle, but unfortunately that's how it behaves right now. If we changed the behavior now, it would break for everyone binding in standard callbacks, so I'm unsure really want to do other than ask for more information from the androidx.lifecycle maintainers.

**Comment by ZacSweers** [comment] 2020-05-10 04:04
Closing this out as this is just a nuance of how the lifecycle observer APIs are

**Closed by ZacSweers** 2020-05-10 04:04 UTC
Labels: Needs info
